// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var SearchBar$ReactTemplate = require("./SearchBar.bs.js");
var SearchResult$ReactTemplate = require("./SearchResult.bs.js");
var VolumeModules$ReactTemplate = require("./VolumeModules.bs.js");

var component = ReasonReact.reducerComponent("SearchContainer");

function reducer(action, state) {
  if (typeof action === "number") {
    return /* UpdateWithSideEffects */Block.__(2, [
              /* record */[
                /* searchText */state[/* searchText */0],
                /* isLoading */true,
                /* volumes */state[/* volumes */2]
              ],
              (function (_self) {
                  var query = _self[/* state */1][/* searchText */0];
                  VolumeModules$ReactTemplate.Api[/* fetchData */0](query).then((function (searchResult) {
                          Curry._1(_self[/* send */3], /* UpdateResults */Block.__(1, [searchResult]));
                          return Promise.resolve(/* () */0);
                        }));
                  return /* () */0;
                })
            ]);
  } else if (action.tag) {
    return /* Update */Block.__(0, [/* record */[
                /* searchText */state[/* searchText */0],
                /* isLoading */state[/* isLoading */1],
                /* volumes */action[0]
              ]]);
  } else {
    return /* Update */Block.__(0, [/* record */[
                /* searchText */action[0],
                /* isLoading */state[/* isLoading */1],
                /* volumes */state[/* volumes */2]
              ]]);
  }
}

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var match = _self[/* state */1];
              return React.createElement(React.Fragment, undefined, ReasonReact.element(undefined, undefined, SearchBar$ReactTemplate.make((function (searchText) {
                                    return Curry._1(_self[/* send */3], /* UpdateSearchText */Block.__(0, [searchText]));
                                  }), (function (param) {
                                    return Curry._1(_self[/* send */3], /* Search */0);
                                  }), /* array */[])), ReasonReact.element(undefined, undefined, SearchResult$ReactTemplate.make(match[/* volumes */2], /* array */[])));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* searchText */"",
                      /* isLoading */false,
                      /* volumes : [] */0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.reducer = reducer;
exports.make = make;
/* component Not a pure module */
