// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var VolumeCard$ReactTemplate = require("./VolumeCard.bs.js");

var component = ReasonReact.statelessComponent("SearchResult");

function make(volumes, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          style: {
                            textAlign: "center"
                          }
                        }, $$Array.of_list(List.map((function (volume) {
                                    return React.createElement("div", {
                                                key: volume[/* id */0],
                                                style: {
                                                  border: "solid 1px",
                                                  margin: "20px",
                                                  padding: "20px"
                                                }
                                              }, ReasonReact.element(undefined, undefined, VolumeCard$ReactTemplate.make(volume, /* array */[])));
                                  }), volumes)));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
