// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("VolumeCard");

function make(volume, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var authors = volume[/* info */1][/* authors */0];
              var publisher = volume[/* info */1][/* publisher */3];
              var volumeUrl = "https://books.google.co.id/books?id=" + volume[/* id */0];
              var authorsNode = authors !== undefined ? React.createElement("div", undefined, "By " + authors.join(", ")) : null;
              var publisherNode = publisher !== undefined ? React.createElement("div", undefined, "Published by " + publisher) : null;
              return React.createElement("a", {
                          style: {
                            color: "inherit",
                            textDecoration: "none"
                          },
                          href: volumeUrl
                        }, React.createElement("div", undefined, React.createElement("img", {
                                  src: volume[/* info */1][/* imageLinks */1][/* thumbnail */0]
                                })), React.createElement("div", undefined, volume[/* info */1][/* title */2], authorsNode, publisherNode));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
