// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function decodeImageLinks(json) {
  return /* record */[/* thumbnail */Json_decode.field("thumbnail", Json_decode.string, json)];
}

function decodeVolumeInfo(json) {
  return /* record */[
          /* authors */Json_decode.optional((function (param) {
                  return Json_decode.field("authors", (function (param) {
                                return Json_decode.array(Json_decode.string, param);
                              }), param);
                }), json),
          /* imageLinks */Json_decode.field("imageLinks", decodeImageLinks, json),
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* publisher */Json_decode.optional((function (param) {
                  return Json_decode.field("publisher", Json_decode.string, param);
                }), json)
        ];
}

function decodeVolume(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.string, json),
          /* info */Json_decode.field("volumeInfo", decodeVolumeInfo, json)
        ];
}

function decodeVolumes(json) {
  return Json_decode.field("items", (function (param) {
                return Json_decode.list(decodeVolume, param);
              }), json);
}

var Decode = /* module */[
  /* decodeImageLinks */decodeImageLinks,
  /* decodeVolumeInfo */decodeVolumeInfo,
  /* decodeVolume */decodeVolume,
  /* decodeVolumes */decodeVolumes
];

function fetchData(query) {
  return fetch("https://www.googleapis.com/books/v1/volumes?key=AIzaSyCM7gQbGPgfTbCZHubXncrVi1MRcPkN37M&q=" + query).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(decodeVolumes(json));
              }));
}

var Api = /* module */[/* fetchData */fetchData];

exports.Decode = Decode;
exports.Api = Api;
/* No side effect */
